default: &default
  adapter: postgresql
  encoding: unicode
  database: four_color_bot_development
  host: localhost
  pool: 5

development:
  <<: *default
  user: postgres
  password: root

test:
  <<: *default
  database: four_color_bot_test
  user: postgres
  password: root

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
